# Generated by Django 5.2.3 on 2025-08-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0009_conta_brasao_instituicao_conta_logo_conta_and_more'),
        ('eventos', '0010_remove_evento_arte_convite_comunicacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='eventos.comunicacao')),
                ('municipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinos_comunicacao', to='atendimentos.municipe')),
            ],
            options={
                'verbose_name': 'Destinatário',
                'verbose_name_plural': 'Destinatários',
                'unique_together': {('comunicacao', 'municipe')},
            },
        ),
        migrations.CreateModel(
            name='LogDeEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha')], max_length=10)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('detalhe_erro', models.TextField(blank=True, null=True, verbose_name='Detalhe do Erro')),
                ('comunicacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='eventos.comunicacao')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.destinatario')),
            ],
        ),
    ]
